// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_web_api_app.Data;

namespace my_web_api_app.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220904082731_AddOrderSchema")]
    partial class AddOrderSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_web_api_app.Data.Good", b =>
                {
                    b.Property<Guid>("GoodCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("GoodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeCode")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("GoodCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("Good");
                });

            modelBuilder.Entity("my_web_api_app.Data.Order", b =>
                {
                    b.Property<Guid>("OrderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrderCode");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("my_web_api_app.Data.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoodCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderCode", "GoodCode");

                    b.HasIndex("GoodCode");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("my_web_api_app.Data.Type", b =>
                {
                    b.Property<int>("TypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeCode");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("my_web_api_app.Data.Good", b =>
                {
                    b.HasOne("my_web_api_app.Data.Type", "Type")
                        .WithMany("Goods")
                        .HasForeignKey("TypeCode");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("my_web_api_app.Data.OrderDetail", b =>
                {
                    b.HasOne("my_web_api_app.Data.Good", "Good")
                        .WithMany("OrderDetails")
                        .HasForeignKey("GoodCode")
                        .HasConstraintName("FK_OrderDetail_Good")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("my_web_api_app.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK_OrderDetail_Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("my_web_api_app.Data.Good", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("my_web_api_app.Data.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("my_web_api_app.Data.Type", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
